### PR TITLE
fix: ssl version in opensearch

### PR DESCRIPTION
**Pull request by joseacl**
Fixes https://github.com/kube-logging/logging-operator/issues/1088 together with this PR https://github.com/kube-logging/logging-operator/pull/1330

### CODE REVIEW

**Comment by genofire** [comment]
Hrelm charts should follow semantic versioning.
so if you call your commit/PR a fix, please increase the patchlevel not minor.

**Comment by joseacl** [comment]
> Hrelm charts should follow semantic versioning. so if you call your commit/PR a fix, please increase the patchlevel not minor.
> 
> or rename the commit to a **feat**

Hi @genofire 

I've already rename the commit message.

**Review by genofire — APPROVED** [review]

**Comment by pepov** [comment]
Sorry for getting here this late... I've edited the PR so that we only increment the patch version, thus we can stay in sync with the image major+minor version

**Comment by gthieleb** [comment]
@pepov Is this PR resolving compatibility with opensearch v2?

**Comment by pepov** [comment]
No I think it doesn't, it's just adding a missing field

**Comment by gthieleb** [comment]
Ok, thanks. Do you know if there is a plan for adding v2 opensearch support.

**Comment by pepov** [comment]
I don't know a specific tracking issue, feel free to add one

**Pull request merged**
